// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwfDwTGLQn17raPK_6ZPC7xbOrsnyQj44',
    appId: '1:199809536282:web:b861f199943e1955b39ca3',
    messagingSenderId: '199809536282',
    projectId: 'testing-cli-c57d9',
    authDomain: 'testing-cli-c57d9.firebaseapp.com',
    storageBucket: 'testing-cli-c57d9.appspot.com',
    measurementId: 'G-68SG7JE1JT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGDhYcwp1Yjx5DgvVkMDjx7IQQjBKfBC4',
    appId: '1:199809536282:android:d1f4a5ac166ba668b39ca3',
    messagingSenderId: '199809536282',
    projectId: 'testing-cli-c57d9',
    storageBucket: 'testing-cli-c57d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEhDcx11RRCwxiT7XErfIbag94KZA5G4s',
    appId: '1:199809536282:ios:92327d4a19099138b39ca3',
    messagingSenderId: '199809536282',
    projectId: 'testing-cli-c57d9',
    storageBucket: 'testing-cli-c57d9.appspot.com',
    iosClientId: '199809536282-bhhr01o5577cttr91e6krbg3320mc81m.apps.googleusercontent.com',
    iosBundleId: 'com.example.translatorApp',
  );
}
